#!/bin/bash
# controls for audio

# Using pulse audio
MIXER="pulse"
CONTROL="Master"

# account for left and right disparity
readarray -t percentages <<< $(amixer -D pulse get Master | sed -n "s/  Front [A-Za-z]*: Playback [0-9][0-9]* \[\([0-9]*\)%] \[[a-z]*\]/\1/p")

percent=${percentages[0]}
color="#FFFFFF"

mute=$(amixer -D pulse get Master | sed -n "s/  Front Left: Playback [0-9][0-9]* \[[0-9]*%] \[\([a-z]*\)\]/\1/p")

output=""
if [[ $mute == on ]]; then
  if (( ${percent} == 0 )); then
    output=""
  elif (( ${percent} > 0 && ${percent} <= 50 )); then
    output=""
  elif (( ${percent} > 50 )); then
    output=""
fi
else
  output=""
fi

if (( ${percent} > 100 && ${percent} <= 125 )); then
    color="#FFB923"
elif (( ${percent} > 125 )); then
    color="#FF0027"
fi

if (( ${percent} > 150 )); then
    $(pactl set-sink-volume 0 150%)
fi

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
  message="<span foreground=\"$color\">${output} ${percent}%</span>"
else
  message="<span foreground=\"$color\">${output}</span>"
fi

echo $message

exit 0

