#!/bin/bash
# controls for audio

percent=$(amixer -D pulse get Master | grep "Left:" | grep -E -o '[0-9][0-9]?%')

if (( ${percent%?} == 0 )); then
  echo 
elif (( ${percent%?} > 0 && ${percent%?} <= 50 )); then
  echo 
elif (( ${percent%?} > 50 && ${percent%?} <= 100 )); then
  echo 
fi

exit 0

