#!/bin/bash

percent=$(acpi |grep -E -o '[0-9][0-9]?[0-9]?%')

if (( ${percent%?} <= 20 )); then
  echo  
elif (( ${percent%?} > 20 && ${percent%?} <= 40 )); then
  echo 
elif (( ${percent%?} > 40 && ${percent%?} <= 60 )); then
  echo 
elif (( ${percent%?} > 60 && ${percent%?} <= 80 )); then
  echo 
elif (( ${percent%?} > 80 && ${percent%?} <= 100 )); then
  echo 
fi

exit 0

