#!/bin/bash

details=$(acpi)
percent=$(echo $details | grep -E -o '[0-9][0-9]?[0-9]?%' | tr -d '%')
condition=$(echo $details | egrep -o -m1 'Discharging|Charging|AC|Full|Unknown')
remaining=$(echo $details | egrep -o -m1 '[0-9][0-9]:[0-9][0-9]')

#There are 8 colors that reflect the current battery percentage when 
#discharging
dis_colors=("${C1:-#FF0027}" "${C2:-#FF3B05}" "${C3:-#FFB923}" 
            "${C4:-#FFD000}" "${C5:-#E4FF00}" "${C6:-#ADFF00}"
            "${C7:-#6DFF00}" "${C8:-#10BA00}")
charging_color="${CHARGING_COLOR:-#00AFE3}"
full_color="${FULL_COLOR:-#FFFFFF}"
ac_color="${AC_COLOR:-#535353}"


if (( ${percent} <= 20 )); then
  icon=" "
elif (( ${percent} > 20 && ${percent} <= 40 )); then
  icon=""
elif (( ${percent} > 40 && ${percent} <= 60 )); then
  icon=""
elif (( ${percent} > 60 && ${percent} <= 80 )); then
  icon=""
elif (( ${percent} > 80 )); then
  icon=""
fi

case "${condition}" in
"Charging")
  icon=" $icon"
  color="$charging_color"
;;
"Full")
  color="$full_color"
;;
"AC")
  color="$ac_color"
;;
"Discharging"|"Unknown")
  if (( $percent >= 0 && $percent < 10 )); then
    color="${dis_colors[0]}"
  elif (( $percent >= 10 && $percent < 20 )); then
    color="${dis_colors[1]}"
  elif (( $percent >= 20 && $percent < 30 )); then
    color="${dis_colors[2]}"
  elif (( $percent >= 30 )); then
    color="$full_color"
  fi
;;
esac

if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
  message="<span foreground=\"$color\">$icon $percent% $remaining</span>"
else
  message="<span foreground=\"$color\">$icon</span>"
fi

echo $message

exit 0

