# XDG config
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"

# ZSH config
export ZDOTDIR="$HOME/.config/zsh"
export HISTFILE="$HOME/.config/zsh/history"
export HISTSIZE=500
export SAVEHIST=500

# history files bin or hide in cache
export LESSHISTFILE="/dev/null"
export PYTHON_HISTORY_FILE="$HOME/.cache/python_history"
export MYSQL_HISTFILE="$HOME/.cache/mysql_history"

# Default programs:
export EDITOR="nvim"
export BROWSER="brave"

# PATH Edits
export PATH="$PATH:$HOME/.local/bin"

# npm config home
# export npm_config_prefix="$HOME/.local"

[ -f "$XDG_CONFIG_HOME/zsh/zshenv.local" ] && source "$XDG_CONFIG_HOME/zsh/zshenv.local"
