#!/bin/sh

# System
alias bctl='bluetoothctl'
alias btc='bluetoothctl connect 00:1B:66:CD:DA:D9'
alias btd='bluetoothctl disconnect 00:1B:66:CD:DA:D9'
alias sp='sudo poweroff'

# VMeet
alias vmeet-db='docker exec -it vmeet-vmeet-mysql-db-1 mysql -u root --password=root -D vmeet-db'

# Pacman
alias pcrd='sudo pacman -Qqdt | sudo pacman -Rs -'
