#!/bin/sh

# colour default
alias ls='ls -G --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# shortenings
alias vim='nvim'
alias open='xdg-open'
alias tm='tmux new-session -A -s main'

# arg aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'


# containers
alias dc='docker-compose'
alias dcb='docker-compose build'
alias dcu='docker-compose up -d'
alias dcd='docker-compose down'
alias dcr='dcd && dcu'

# git
alias g='git'
alias ga='git add'
alias gb='git branch'
alias gba='git branch -a'
alias gch='git checkout'
alias gco='git commit'
alias gcom='git commit -m'
alias gic='(git switch main 2> /dev/null || git switch develop 2> /dev/null || git switch master) && git pull'
alias glog='git log --branches --remotes --tags --graph --decorate --pretty=format:"%C(yellow)%h %Cgreen%ad %Cblue%an%Cred%d %Creset%s" --date=short'
alias giop='$EDITOR $(git status -s | awk "{print \$2}")'
alias gip='git push -u origin HEAD'
alias gir='git reset HEAD'
alias gs='git status'

if [[ -e "$HOME/.config/shell/aliases_local" ]]; then
    source "$HOME/.config/shell/aliases_local"
fi

# date
alias utcdate='date -u +"%Y-%m-%dT%H:%M:%SZ"'
