#!/bin/sh

# colour default
alias ls='ls -G --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# shortenings
alias vim='nvim'
alias open='xdg-open'

# arg aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'


# containers
alias dcb='docker-compose build'
alias dcu='docker-compose up'
alias dcd='docker-compose down'

# git
alias gib='git branch -a'
alias gic='(git switch main || git switch develop 2> /dev/null || git switch master) && git pull'
alias gis='git status'
alias gip='git push -u origin HEAD'
alias gich='git checkout'
alias gico='git commit -am'
alias gilog='git log --branches --remotes --tags --graph --decorate --pretty=format:"%C(yellow)%h %Cgreen%ad %Cblue%an%Cred%d %Creset%s" --date=short'

if [[ -e "$HOME/.config/shell/aliases_local" ]]; then
    source "$HOME/.config/shell/aliases_local"
fi
