#!/bin/bash

giclr(){
    git fetch -p
    for branch in $(git branch -vv | grep "gone" | awk '{print $1}'); do
        git branch -D $branch
    done
}

tmux-attach(){
    session_id=$(tmux ls &>/dev/null | sed -n '/attached/! s/\([0-9]\).*/\1/p' | head -n 1)
    [[ -n $session_id ]] && tmux attach -t $session_id || tmux
}
